<a href="https://colab.research.google.com/github/K-K-0/MLP-Assignments/blob/main/Copy_of_Practice_Oppe_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Max Marks: 90
Part 1 Marks: 45

Part 2 Marks: 45

# Dataset Description

Use the following dataset for Part1: [dataset](https://drive.google.com/file/d/1cHGfVASFltupF3uLF3LoYXiwftoLpk3u/view?usp=sharing)

***Download the dataset in your machine, then upload it in colab.***

Following is description of different columns in the dataset.

1. `CRIM`: per capita crime rate in the vicinity

2. `ZN`: amount of residential land reserved in the vicinity.

3. `INDUS`: proportion of industrial land reserved  nearby (in square kilometers)

4. `RIVERSIDE`: If the boundary faces river side (= 1 if tract bounds river; 0 otherwise)

5. `POLINDEX`: polution index

6. `RM`: number of rooms in the house.

7. `AGE`: Age of the property in years.

8. `DIS`: weighted distances to the major economic centres (in kilometers)

9. `HIGHWAYCOUNT`: Number of highways within 5 KM of distance.

10. `TAX`: full-value property-tax rate per 1 lac.

11. `PTRATIO`: student-teacher ratio in the vicinity.

12. `IMM`: Immigration index in the vicinity.

13. `BPL`: % of below poverty line population in the vicinity.

14. `PRICE`: Price of the home in lacs, this is the target column.

# Part 1: Data preprocessing

### **Note**: For numerical type questions, always enter the answer correct upto 3 decimal places without rounding off, unless otherwise stated.

##Q1. [1 marks][MCQ] Which dataset are you using for this exam?

Options:

A) V1

B) V2

C) V3

D) V4

E) V5

Answer: E

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/V1.csv')
df.head()

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,22.991633,NO
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,24.551055,NO
2,10.925905,0.441022,18.322960,2.824833,8.0,-2.0,2.409495,25,666.492973,20.351601,387.061355,19.366070,15.875346,NO
3,0.559027,1.041175,11.114920,0.794952,6.0,9.0,6.898669,4,305.514181,19.787314,391.778647,6.206820,23.007756,NO
4,0.905063,81.167963,3.673369,1.029030,8.0,20.0,10.246463,1,315.913960,17.360439,395.833166,10.827105,21.503177,NO

## Q.2 [2 marks][MCQ] How many samples are there in the dataset?

Options:

A) 4000

B) 5000

C) 6000

D) 7000

Ans: A

In [ ]:
# Solution
df.shape

(4000, 14)

## Q.3 [2 marks][NAT] What is the average house price (in lacs)?


Ans: 24.355 [Range 24.30 to 24.40]

In [ ]:
# Solution
np.average(df['PRICE'])

np.float64(24.355923220694248)

## Q.4 [3 marks][MCQ] How many houses have 5 or more rooms?

Options:

A) 3953

B) 3921

C) 3896

D) 3932

E) 3925

F) None of these

ANS: A

In [ ]:
# Solution
df[df['RM'] >= 5].count()

CRIM            3953
ZN              3953
INDUS           3953
POLINDEX        3953
RM              3953
AGE             3953
DIS             3953
HIGHWAYCOUNT    3953
TAX             3953
PTRATIO         3953
IMM             3953
BPL             3953
PRICE           3953
RIVERSIDE       3953
dtype: int64

## Q.5 [3 marks][NAT] What is the average price of the top 10 most expensive houses (in lacs)?

Ans: 52.365

[Range: 52.31 to 52.41]

In [ ]:
# Solution
np.average(df['PRICE'].mode()[-10:])

np.float64(52.36590175716407)

## Q.6 [2 marks][MCQ] What is the total number of missing or unknown values in the number of rooms feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)

Options:

A) 40

B) 71

C) 99

D) 61

E) 68

F) None of these

Ans: A

In [ ]:
# Solution
# count of -1 is 40 so Room numbers can't be minus so missing values is 40
df['RM'].value_counts()

RM
 7.0     1733
 6.0      961
 8.0      894
 9.0      276
 5.0       47
 10.0      40
-1.0       40
 4.0        7
 11.0       2
Name: count, dtype: int64

## Q.7 [2 marks][MCQ] What is the total number of missing or unknown values in the age feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)

Options:

A) 50

B) 83

C) 74

D) 64

E) 59

F) None of these

Ans: A

In [ ]:
# df['AGE'] = df['AGE'].mask((df['AGE'] < 0), np.nan)
# df[df['AGE'] < 0].sum()
# df['AGE'].value_counts()
(df['AGE'] < 0).sum()

np.int64(50)

## Q.8 [2 marks][MCQ] What is the total number of missing or unknown values in the `RIVERSIDE` feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)

Options:

A) 88

B) 101

C) 56

D) 62

E) 80

F) None of these

Ans: A

In [ ]:
# Solution
df['RIVERSIDE'].value_counts()

RIVERSIDE
NO         3595
YES         317
UNKNOWN      88
Name: count, dtype: int64

## Q.9 [3 marks][MCQ] How many houses are on riverside and were built within last 50 years (i.e. a house 50 years old or younger)? For this question, ignore the rows that have missing values in either riverside feature or age feature.

Options:

A) 44

B) 42

C) 52

D) 43

E) 37

F) None of these

Ans: A

In [ ]:
# Solution
((df['RIVERSIDE'] == 'YES') & (df['AGE'] <= 50)).sum()

np.int64(53)

## Q.10 [3 marks][MCQ] How many houses are near to exactly 6, 7 or 8 highways (all three inclusive)?

Options:

A) 1211

B) 1174

C) 1234

D) 938

E) 1209

F) None of these

Ans: A

In [ ]:
((df['HIGHWAYCOUNT'] >= 6) & (df['HIGHWAYCOUNT'] <= 8)).sum()

np.int64(1211)

## Q.11 [4 marks][MCQ] Create a column 'CATEGORY' and divide the houses in categories as following:

- Category 1: house price <10 lacs
- Category 2: 10 lacs <= house price <20 lacs
- Category 3: 20 lacs <= house price <30 lacs
- Category 4: 30 lacs <= house price <40 lacs
- Category 5: house price >=40 lacs


Which category has the highest number of records?

Options:

A) 1

B) 2

C) 3

D) 4

E) 5

F) There is a tie between multiple categories

Ans: C

In [ ]:
# Solution
# (df['PRICE'] < 10).sum()
# ((df['PRICE'] >= 10) & (df['PRICE'] < 20)).sum()
# ((df['PRICE'] >= 20) & (df['PRICE'] < 30)).sum()
# ((df['PRICE'] >= 30) & (df['PRICE'] < 40)).sum()
(df['PRICE'] >= 40).sum()

np.int64(268)

# Apply Pre processing

## Divide the data into training and test sets
- Replace the respective missing or unknown values in features room count, riverside and age with `np.nan`.
- Keep 30% of the data as test set.
- Use random_state as 0
- `PRICE` is the target, rest of the columns are the features.
<!-- - In 'RIVERSIDE' feature, replace 'NO' with 0 and 'YES' with 1. -->
- Apply train test split.

**Hint**: look for the documentation of the usual function that divides the data into training and test datasets.

## Q.12 [2 marks][MCQ] What is the number of samples in the training set?

Options:

A) 2800

B) 2900

C) 3000

D) 3100

Ans: A

In [ ]:
df['AGE'] = df['AGE'].mask((df['AGE'] < 0), np.nan)

df['RM'] = df['RM'].mask((df['RM'] < 0), np.nan)

df['RIVERSIDE'] = df['RIVERSIDE'].replace('UNKNOWN', np.nan)

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop('PRICE', axis=1)
y = df['PRICE']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)
X_train.shape

(2800, 13)

In [ ]:
print(X_train['RIVERSIDE'].unique())
print(X_train['RIVERSIDE'].nunique())

['NO' 'YES' nan]
2

### Apply following preprocessing steps:


- Drop `CATEGORY` column
- `CRIM`: min max scaling
- `ZN`: min max scaling
- `INDUS`: standard scaling
- `POLINDEX`: min max scaling
- `DIS`: min max scaling
- `HIGHWAYCOUNT`: min max scaling
- `TAX`: min max scaling
- `PTRATIO`: min max scaling
- `IMM`: min max scaling
- `BPL`: min max scaling
- `RM`: impute with median then min max scaling
- `AGE`: impute with mean then min max scaling
- `RIVERSIDE`: Impute with most frequent value then one hot encode.

NOTE:
1. Make sure to preprocess the features in the above order exactly. Answer of Q.16 depends upon correct order of featuring processing.
2. You may have to use multiple instances of a trasnformer for this question.

In [ ]:
minmax = ['CRIM', 'ZN', 'POLINDEX', 'DIS', 'HIGHWAYCOUNT', 'TAX', 'PTRATIO', 'IMM', 'BPL']

In [ ]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline


min = Pipeline([
    ('scale', MinMaxScaler()),
])

indus_pipeline = Pipeline([
    ('scale', StandardScaler())
])

rm_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', MinMaxScaler())
])

age_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='mean')),
    ('scale', MinMaxScaler())
])

river_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('encode', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num',min, minmax),
    ('indus', indus_pipeline, ['INDUS']),
    ('rm', rm_pipeline, ['RM']),
    ('age', age_pipeline, ['AGE']),
    ('river', river_pipeline, ['RIVERSIDE'])
])
preprocessor.set_output(transform='pandas')

X_trans = preprocessor.fit_transform(X_train)
X_test_t = preprocessor.transform(X_test)

X_trans.head()

,num__CRIM,num__ZN,num__POLINDEX,num__DIS,num__HIGHWAYCOUNT,num__TAX,num__PTRATIO,num__IMM,num__BPL,indus__INDUS,rm__RM,age__AGE,river__RIVERSIDE_NO,river__RIVERSIDE_YES
3336,0.189700,0.004561,0.033842,0.124347,0.192308,0.374853,0.829378,0.989745,0.419050,-0.239852,0.428571,0.860000,1.0,0.0
2540,0.036362,0.202330,0.162887,0.271862,0.115385,0.069331,0.690556,0.976549,0.140763,-0.529958,0.571429,0.640453,0.0,1.0
332,0.531739,0.010602,0.652160,0.085051,0.884615,0.912012,0.792344,0.937695,0.047807,1.194743,0.142857,0.970000,1.0,0.0
852,0.358052,0.009848,0.301953,0.067032,0.192308,0.410736,0.214812,0.658560,0.436328,1.289528,0.285714,0.960000,1.0,0.0
1036,0.110154,0.017579,0.158678,0.325495,0.192308,0.223330,0.658217,0.992762,0.324922,-0.038482,0.714286,0.560000,1.0,0.0

## Q.13 [5 marks][MCQ] How many features are there after performing above transformation?

Options:

A) 14

B) 15

C) 16

D) 17

E) 18

Ans: A

In [ ]:
X_trans.shape #but and is 14 because i use OneHotEncoder wich make redundant feature in RIVERSIDE feature

(2800, 14)

## Q.14 [2 marks][NAT] What is the mean of the transformed test data (features only)?

Note : Compute the mean of the whole feature matrix i.e. mean of all values in the transformed test feature matrix

Ans: 0.38 [Range: 0.33 to 0.43]

In [ ]:
# Solution
np.mean(X_test_t)

np.float64(0.3861745655097562)

---

# Model Building

Load the dataset.

The file has no index column.\
The last column is the target column.\
The first row of the file has column ids

[Click here to view the dataset (V3)](https://drive.google.com/file/d/1OtwemNuw0qilXAutyuZEjOscZVKuD7Tv/view)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/NPPE1_ModelBuilding3.csv')
df.head()

## Split the dataset into train dataset and test dataset in the following manner

Use train_test_split to split the dataset into train and test dataset with test size equal to 0.3(i.e.30%) and random_state equal to 42. Let other parameters have default values.

Columns except the last column should be the feature matrix (X_train or X_test)

Last column will be the label vector.

In [ ]:
# Solution
from sklearn.model_selection import train_test_split
X = df.drop('14', axis=1)
y = df['14']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
y_train.values.reshape(-1,1).shape

## (Common instructions for Q.1, Q.2 and Q.3)

Train the ridge model on the training data with the following parameters:

alpha = 10
solver = 'saga'
tol = 1e-4
random_state = 42

In [ ]:
# Solution
from sklearn.linear_model import Ridge
rid = Ridge(alpha=10, solver='saga', tol=1e-4, random_state=42)

## Q1) Enter the value of $R^2$ score on the test dataset.

Ans: 0.66

(Type: Range) 0.656,0.666

In [ ]:
from sklearn.metrics import r2_score
# Solution
rid.fit(X_train, y_train.values.reshape(-1,1))
r2_score(y_test, rid.predict(X_test))

## Q2) What is the index of most important feature? Note the index starts from 0. Ignore the intercept for this question.

Ans: 9

In [ ]:
# Solution
abs(rid.coef_)

## Q3) What is the index of least important feature? Note the index starts from 0. Ignore the intercept for this question.

Ans: 0

In [ ]:
# Solution
abs(rid.coef_).min()

## (Common Instructions for Q.4 and Q.5)
Take SGDRegressor(random_state = 42) estimator with GridSearchCV. Hyperparameter tuning to be done over the following parameters:


penalty as ['l1', 'l2']\
alpha values as [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]\
values of tol as [1e-4, 1e-3, 1e-2, 1e-1]\
Use cross-validation = 5\
Set scoring as neg_mean_absolute_error


Use the best model from above hyper parameter tuning process to answer following questions:

In [ ]:
# Solution
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDRegressor
sgd = SGDRegressor()

params = {
    "alpha": [1e-5, 1e-4, 1e-3, 1e-2, 1e-1],
    "penalty": ['l1', 'l2'],
    "tol": [1e-4, 1e-3, 1e-2, 1e-1]
}
grid = GridSearchCV(
    sgd,
    params,
    cv=5,
    scoring="neg_mean_absolute_error",
    verbose=True
)

grid.fit(X_train, y_train.values.reshape(-1,1))

## Q4) What is the best penalty?

> A l1\
> B l2

Ans: B

In [ ]:
# Solution
grid.best_params_

## Q5) What will be value of mean absolute error on the test dataset?

Ans: 3.81

(Type: Range) 3.808,3.818

In [ ]:
# Solution
from sklearn.metrics import mean_absolute_error
best_model = grid.best_estimator_

mean_absolute_error(y_test, best_model.predict(X_test))

## (Common Instructions for Q.6 and Q.7)

Create a pipeline of the PCA() as transformer and Lasso as an estimator.


Use GridSearchCV for tuning the hyperparameters of the created pipeline on training dataset.

Values of n_components for PCA to be [0.9, 0.95]\
lasso alpha value to be taken as : [10, 1, 0.01, 0.001]\
scoring : neg_mean_absolute_error.\
Use 5 fold cross validation.\
n_jobs = -1 (negative one) [it helps in using all the computational power to run this job]\
(Note: Kindly ignore the warning.)

In [ ]:
# Solution
from sklearn.decomposition import PCA
from sklearn.linear_model import Lasso
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('transformer', PCA()),
    ('estimator', Lasso())
])

params = {
    'transformer__n_components': [0.9, 0.95],
    'estimator__alpha': [10,1,0.01, 0.001]
}

grid_ = GridSearchCV(
    pipe,
    params,
    scoring='neg_mean_absolute_error',
    cv=5,
    n_jobs=-1
)

## Q6)  If we fit the pipeline on the training dataset, what will be the $R^2$ score on the test dataset?

Ans: 0.62

(Type: Range) 0.623,0.633

In [ ]:
# Solution
grid_.fit(X_train, y_train)
r2_score(y_test, grid_.predict(X_test))

## Q7)  How much variance is explained (Eigen value) by the first principle component?

ANs: 1.16

(Type: Range) 1.158,1.168

In [ ]:
# Solution
pca = grid_.best_estimator_.named_steps['transformer']
pca.explained_variance_[0]

## Q8) Create a pipeline of the PolynomialFeatures as transformer and Lasso as an estimator with the following parameters:
  - For PolynomialFeatures:
    - interaction_only = False
    - degree = 2
  - For Lasso:
    - alpha = 1
    - warm_start = True
    - random state as 0

Fit the pipeline on the training dataset and find the $R^2$ score on the test dataset.

Ans: 0.15

(Type: Range) 0.152,0.162

In [ ]:
# Solution
from sklearn.preprocessing import PolynomialFeatures

pi = Pipeline([
    ('trans', PolynomialFeatures(interaction_only=False, degree=2)),
    ('esti', Lasso(alpha=1, warm_start=True, random_state=0))
])

pi.fit(X_train, y_train)
r2_score(y_test, pi.predict(X_test))

## Q9) If you eliminate 1 feature with recursive feature elimination, which feature will be eliminated?

Type the index of the eliminated feature (index starts from 0).


Use LinearRegression model with default parameters as an estimator.


Use processed training data.

Ans: 2

In [ ]:
# Solution
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

select = RFE(LinearRegression(), n_features_to_select=X_train.shape[1] - 1)
select.fit(X_train, y_train)
fe = np.where(select.ranking_ > 1)
fe